filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log
  json.keys_under_root: true
  json.message_key: log
  processors:
    - add_docker_metadata: ~

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

logging.level: info

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

output.logstash:
  hosts: ["logstash:5044"]

logging.metrics.enabled: false 